version: "3.8"
services:
  spark-master:
    build: .
    image: spark-bio:latest
    container_name: spark-master
    network_mode: host
    restart: unless-stopped
    volumes:
      - /mnt/genome:/mnt/genome
      - /vol/fob-vol7/mi21/kimhongs/spark-genome-pipeline:/workspace/pipeline
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_MASTER_HOST=141.20.38.81
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_MASTER_WEBUI_HOST=0.0.0.0
      - SPARK_LOCAL_IP=141.20.38.81
    command: >
      bash -lc "start-master.sh & sleep 2; tail -F /opt/spark/logs/*master*.out"


